name: Build and deploy Python app to Azure Web App - MyGame

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment and install dependencies
        run: |
          cd MyProject
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd MyProject
          zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_83BC0F66F0C04236BC85049D401CEC13 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E437CF63414D49E5A3BEDBEA20AE0AF8 }}
          subscription-id
